name: CI - Regression Tests

env:
    TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
    TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

on:
  push:
    branches: [ main ]

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npx playwright install chromium
      - run: npx playwright test --grep @regression
      - if: always()
        run: npm install -g allure-commandline
      - if: always()
        run: npm run allure:generate
      - if: always()
        uses: actions/configure-pages@v5
        with:
          enablement: true
      - if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: allure-report
      - id: deployment
        if: always()
        uses: actions/deploy-pages@v4
