name: CI - Regression Tests

env:
    TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
    TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npx playwright install chromium
      - run: npx playwright test --grep @regression
      - if: always()
        run: npm install -g allure-commandline
      - if: always()
        run: npm run allure:generate
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
